GET http://localhost:3000/api/notes

###

POST http://localhost:3000/api/notes/ HTTP/1.1
content-type: application/json

{
    "title": "taslhjgah;kag",
    "body": "aldsfj;lkj;adf"
}

###

POST http://localhost:3000/signup/ HTTP/1.1
content-type: application/json

{
         "username": "HelloThereTest",
        "password": "TestPWFromafgafdRESTCLIENT"
}